apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: silly
  labels:
    role: light-dtk
spec:
  containers:
    - name: light-dtk
      image: image-registry.openshift-image-registry.svc:5000/silly/dtk-light:demo
